### ISSUE TITLE
--msci-create example returns "Segmentation fault"

### ISSUE THREAD

**Issue by simonharnqvist** [bpp/bpp#158]
Hi, I've tried to run the --msci-create example below:

```
tree (((A,B),C),(D,E));

# define labels on some nodes as lowest-common-ancestors of a list of nodes
define V as A,B
define X as A,C
define W as D,E
define R as A,E

# define a hybridization event on edge C-X, coming from edge W-R, and label it as H (the node on C-X) and Y (the node on W-R). Both get a tau parameter (first yes corresponds to H-X), and phi=0.4 (corresponds to H-X)
hybridization C X, W R as H Y tau=yes,yes phi=0.4

# define bidirection between edges H-X and Y-H, label the new nodes as S (on H-X) and T (on Y-H) and phi=0.2 for T->S and 0.3 for S->T
bidirection  H X, H Y as S T phi=0.2,0.3

# define parallel edges
hybridization  A V as P Q phi=0.333
```

`bpp --msci-create msci.txt`

This returns:
```
Parsing definititions file msci.txt ...
Reconstructing species tree ...
Processing hybridization/introgression events ...
Segmentation fault
```
This is using BPP 4.4.0 on CentOS Linux 7.9.2009

Thanks in advance!
Simon

**Comment by simonharnqvist** [comment]
--msci-create works fine under version 4.3.0 - seems likely that there is a bug in 4.4.0

**Comment by xflouris** [comment]
Thanks for the bug report @simonharnqvist . I will check it and get back!
Tomas

**Comment by simonharnqvist** [comment]
@xflouris Perfect, thank you. I have a related question that I hope you don't mind if I hijack this issue for: how do I select the phi values for the tree (e.g. bidirection  H X, H Y as S T **phi=0.2,0.3**)? The manual specifies the phi prior, but what are these values?

**Comment by xflouris** [comment]
The phi values (0.2 and 0.3) are not important for inference. They are just the starting values the program will use for the two phi parameters.
They are only important if you want to simulate data with the phi parameters fixed to those two values.

There is some documentation on the msci-create option [here](https://github.com/bpp/bpp/releases/download/v4.4.1/msci-create.pdf), if that helps.

I also confirm I can reproduce the segmentation fault you get, and will try to get it fixed today. If `--msci-create` is working with v4.3.0 that's fine, but then please use the latest version for inference, as we've changed the way the phi estimates are printed in the summary to be more consistent. In the previous versions (including 4.3.0 I believe) the program will decide to print the introgression probability on either the vertical or horizontal species tree branch depending on how the newick string is formed. In the later versions (>= 4.4.0) the output is consistent independently of the newick notation.

Tomas

**Comment by simonharnqvist** [comment]
Thanks Tomas!

**Comment by xflouris** [comment]
Hi @simonharnqvist ,
it took me longer to get to this issue but I know what the problem is now. We changed the specification of introgressions in the MSci generator in BPP v4.4.0 and newer. In v4.3.0 the first edge was the target while in v4.4.0 the first edge is the source. 
In short, it is fine if you used v4.3.0 to generate the MSci model and then used that or a newer version for inference.

Below I'm decribing the problem you encountered, also for my own record:

The description for the first hybridization event you define

```
# define a hybridization event on edge C-X, coming from edge W-R, and label it as H (the node on C-X) and Y (the node on W-R). Both get a tau parameter (first yes corresponds to H-X), and phi=0.4 (corresponds to H-X)
hybridization C X, W R as H Y tau=yes,yes phi=0.4
```
is correct for v4.3.0, but for v4.4.0 and newer the generator is instructed to create a hybridization event on R-W coming from X-C and label the node as Y (on R-W) and H on X-C. That is, we have two edges, R-Y and H-Y coming into Y.

This is still valid but the problem happens in the next line:
```
# define bidirection between edges H-X and Y-H, label the new nodes as S (on H-X) and T (on Y-H) and phi=0.2 for T->S and 0.3 for S->T
bidirection  H X, H Y as S T phi=0.2,0.3
```
which attempts to creates a bidirection event between X-H and H-Y, going back and forth in time as X-H is the ancestor of H-Y (i.e. node X is the parent of H, and H the parent of Y).

I think you must have taken the example from issue #114 which used the notation from v4.3.0. In v4.4.0+ the notation is different and the same example is shown on page 3 of the [MSci generator documentation](https://github.com/bpp/bpp/releases/download/v4.4.1/msci-create.pdf).
I'm pasting the correct notation here:

```
tree (((A,B)V,C)X,(D,E)W)R;
hybridization R W,X C as Y H tau=yes, yes phi=0.4
bidirection  X H, Y H as S T phi=0.2,0.3
hybridization V A as P Q phi=0.333
```
The segfault happened because of the 'time-travelling' bidirection as I didn't have a check for that in the code. I'm fixing it in the 'dev' version.

Tomas

**Comment by xflouris** [comment]
fixed
