### ISSUE TITLE
sequences longer than expected in seqfile

### ISSUE THREAD

**Issue by JoSprong** [bpp/bpp#184]
Dear Tomás, 

I am currently running bpp for my project but noticed that when the sequences in the seqfile are too long (>1000 bp), bpp halts the run. It gives the error that the sequence is longer than expected.  Is there a way to still include those sequences in the alignment file that are over 1000bp long? Or what do you recommend in this case (other than removing those sequences)?

I am looking forward to hearing from you.

Best wishes,
Joëlle

**Comment by xflouris** [comment]
Hi Joëlle,
There is no limit on the length of the sequences BPP can take, and it's likely your phylip file is malformed. Note that the sequence file is a collection of blocks (phylip formats) appearing one after the other, each representing a sequence alignment and each has its own header which includes two numbers: number of sequences and sequence length for the current block.

It's possible that some blocks were assigned an incorrect sequence length. Can you double-check the locus BPP mentions is wrong? If you don't know which one it is, a good strategy is to modify the `nloci` variable to use only half of the loci. If the problem still occurs continue by halving the nloci, otherwise increase nloci by half of the current value, until you reach the malformed locus.

Best,
Tomas

**Comment by JoSprong** [comment]
Dear Tomas,

Thank you for your quick reply. You are indeed correct, there was something wrong with the phylip file. For my data, I have >500 loci in nexus format that are eventually combined and formatted in this single phylip file. Those sequence alignments longer than 1000bp are written in an interleaved pattern, and I think that was the main issue. I fixed it now, and everything runs as it should! The length of the sequences was not the problem.

Thanks for your help and feedback!

Best,
Joëlle
