### ISSUE TITLE
Fix qsort callback functions to work with BSD variant of qsort

### ISSUE THREAD

**Issue by xflouris** [bpp/bpp#75]
GNU/Linux uses the GNU variant of `qsort()` while MAC OSX uses the BSD variant.
Both variants process three return values from the callback function that comparing the two passed variables `a` and `b`.
* 1 means `a > b`
* 0 means `a == b`
* -1 means `a < b`

In the GNU variant of qsort it is sufficient to implement the callback as `return a > b`, which returns only either 1 or 0. In case a 0 is returned, the GNU variant always swaps the two values (i.e. it considers 0 in the same way as -1). The BSD version does not use the same consideration and therefore values may not be sorted correctly.

**Comment by ziheng-yang** [comment]
interesting difference between the two compilers 
but both are clearly correct in this case.  the 
behavior when a == b should be undefined since 
both swapping and not swapping is correct, so

return a > b;

is not correct.  perhaps

return a > b ? 1 : (a < b ? -1 : 0);

ziheng




At 09:46 PM 8/29/2018 Wednesday, Tomas Flouri wrote:

**Comment by xflouris** [comment]
fixed
